## Software Installation
# - hosts: all
#   vars:
#     disable_services:
#       - cockpit
#       - dhcpv6-client
#   roles:
#     - role: firewall

- hosts: all
  roles:
    - role: common

# - hosts: dbservers
#   roles:
#     - role: database
    
# - hosts: nfsservers
#   roles:
#     - role: nfs

# - hosts: cacheservers
#   roles:
#     - role: cache

# - hosts: webservers
#   roles:
#     - role: web

# - hosts: balancerservers
#   gather_facts: true
#   roles:
#     - role: balancer


# Configure Firewall Rules
# - hosts: dbservers
#   vars:
#     enable_services:
#       - mysql
#   roles:
#     - role: firewall

# - hosts: nfsservers
#   vars:
#     enable_services:
#       - nfs
#       - rpc-bind
#   roles:
#     - role: firewall

# - hosts: cacheservers
#   vars:
#     enable_services:
#       - redis
#   roles:
#     - role: firewall

# - hosts: webservers
#   vars:
#     enable_services:
#       - http
#   roles:
#     - role: firewall

# - hosts: balancerservers
#   vars:
#     enable_services:
#       - http
#       - https
#   roles:
#     - role: firewall

#ansible-playbook moodle.yml