# - hosts: all
#   remote_user: root
#   gather_facts: true
#   roles:
#     - role: common

# - hosts: dbservers
#   remote_user: root
#   gather_facts: true
#   roles:
#     - role: database
    
- hosts: nfsservers
  remote_user: root
  gather_facts: true
  roles:
    - role: nfs

# - hosts: cacheservers
#   remote_user: root
#   gather_facts: true
#   roles:
#     - role: cache

# - hosts: webservers
#   remote_user: root
#   gather_facts: true
#   roles:
#     - role: web
    
#ansible-playbook -i inventory/main.yml moodle.yml