- hosts: all
  remote_user: root
  gather_facts: true
  vars:
    disable_services:
      - cockpit
      - dhcpv6-client
  roles:
    - role: firewall

# - hosts: all
#   remote_user: root
#   gather_facts: true
#   roles:
#     - role: common

# - hosts: dbservers
#   remote_user: root
#   gather_facts: true
#   roles:
#     - role: database
    
# - hosts: nfsservers
#   remote_user: root
#   gather_facts: true
#   roles:
#     - role: nfs

# - hosts: cacheservers
#   remote_user: root
#   gather_facts: true
#   roles:
#     - role: cache

# - hosts: webservers
#   remote_user: root
#   gather_facts: true
#   roles:
#     - role: web

# - hosts: balancerservers
#   remote_user: root
#   gather_facts: true
#   roles:
#     - role: balancer

# - hosts: all
#   remote_user: root
#   gather_facts: true
#   vars:
#     enable_services:
#       - nfs
#       - http
#     enable_ports:
#       - 3306/tcp
#       - 5432/tcp
#     disable_services:
#       - nfs
#       - http
#     disable_ports:
#       - 3306/tcp
#       - 5432/tcp
#   roles:
#     - role: firewall
    
#ansible-playbook -i inventory/main.yml moodle.yml