---
all:
  # Define the aliases here
  hosts:
    db:
      ansible_host: 192.168.56.119
      ansible_hostname: moodle-db.local
    nfs:
      ansible_host: 192.168.56.118
      ansible_hostname: moodle-nfs.local
    cache:
      ansible_host: 192.168.56.119
      ansible_hostname: moodle-cache.local
    web1:
      ansible_host: 192.168.56.119
      ansible_hostname: moodle-web1.local
    bal:
      ansible_host: 192.168.56.119
      ansible_hostname: moodle-bal.local

# Create a group called webserver and add web1
webservers:
  hosts:
    web1:

dbservers:
  hosts:
    db:

nfsservers:
  hosts:
    nfs:

cacheservers:
  hosts:
    cache:

balservers:
  hosts:
    bal:

# https://notes.benheater.com/books/ansible/page/defining-the-inventory