---
all:
  children:
    webservers:
      hosts:
        192.168.56.119:
    dbservers:
      hosts:
        192.168.56.119:
    nfsservers:
      hosts:
        192.168.56.119:
    cacheservers:
      hosts:
        192.168.56.119:
    balancerservers:
      hosts:
        192.168.56.119: