---
all:
  children:
    webservers:
      hosts:
        192.168.56.118:
    dbservers:
      hosts:
        192.168.56.118:
    nfsservers:
      hosts:
        192.168.56.119:
    cacheservers:
      hosts:
        192.168.56.119: