- name: Ping my hosts
  ansible.builtin.ping:

- name: Print My hostname
  ansible.builtin.debug:
    var: ansible_hostname

- name: Configure MariaDB Repo
  ansible.builtin.shell: curl -LsS https://r.mariadb.com/downloads/mariadb_repo_setup | bash -s -- --mariadb-server-version="mariadb-10.11"
  args:
    warn: false
  notify:
    - update packages