- name: Include variables.
  include_vars: "nfs.yml"

- name: Update all packages
  ansible.builtin.dnf:
    name: "*"
    state: latest
    update_cache: yes

- name: Install NFS prerequisite Packages
  ansible.builtin.package:
    name: 
      - nfs-utils
      - rpcbind
    state: latest

- name: Create moodledata dir
  ansible.builtin.file:
    path: /var/moodledata
    state: directory
    owner: root
    group: root
    mode: '0700'  

- name: Copy exports file.
  template:
    src: exports.j2
    dest: /etc/exports
    owner: root
    group: root
    mode: 0644
  notify: reload nfs

- name: Ensure nfs, rpcbind services are running.
  ansible.builtin.service: 
    name: "{{ item }}" 
    state: started 
    enabled: yes
  with_items:
    - rpcbind
    - nfs-server

- name: Enable NFS FirewallD rules
  ansible.posix.firewalld:
    permanent: true
    service: "{{ item }}"
    state: enabled
  with_items:
    - nfs
    - rpc-bind
  notify: reload firewald