---
- name: Enable firewalld services
  ansible.posix.firewalld:
    permanent: true
    service: "{{ item }}"
    state: enabled
  loop: "{{ enable_services }}"
  notify: reload firewald
  when: enable_services is defined

- name: Enable firewalld ports
  ansible.posix.firewalld:
    permanent: true
    port: "{{ item }}"
    state: enabled
  loop: "{{ enable_ports }}"
  notify: reload firewald
  when: enable_ports is defined

- name: Disable firewalld services
  ansible.posix.firewalld:
    permanent: true
    service: "{{ item }}"
    state: disabled
  loop: "{{ disable_services }}"
  notify: reload firewald
  when: disable_services is defined

- name: Disable firewalld ports
  ansible.posix.firewalld:
    permanent: true
    port: "{{ item }}"
    state: disabled
  loop: "{{ disable_ports }}"
  notify: reload firewald
  when: disable_ports is defined