## Install and configure php
- name: Install and configure php
  ansible.builtin.include_tasks: php.yml

## Install and configure nginx
- name: Install and configure nginx
  ansible.builtin.include_tasks: nginx.yml

## Download Moodle
- name: Download Moodle
  ansible.builtin.include_tasks: moodle.yml

# Moodledata dir
- name: Mount NFS volume if moodledata is in nfs
  ansible.builtin.include_tasks: nfs.yml
  when: mount_moodledata_dir