# Nginx
- name: Generate Diffie-Hellman parameters with the default size (4096 bits)
  community.crypto.openssl_dhparam:
    path: /etc/pki/tls/certs/dhparam.pem
    size: 2048

- name: Install Nginx
  ansible.builtin.package:
    name: nginx
    state: latest

- name: Create snippets dir
  ansible.builtin.file:
    path: /etc/nginx/snippets
    state: directory
    owner: root
    group: root
    mode: '0755'    

- name: Copy nginx config file  
  ansible.builtin.copy:  
    src: nginx.conf  
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: '0644'
    force: true

- name: Copy moodle config file  
  ansible.builtin.copy:  
    src: moodle.conf  
    dest: /etc/nginx/conf.d/moodle.conf
    owner: root
    group: root
    mode: '0644'
    force: true

- name: Copy php-fpm nginx config file  
  ansible.builtin.copy:  
    src: php-fpm.conf  
    dest: /etc/nginx/conf.d/php-fpm.conf
    owner: root
    group: root
    mode: '0644'
    force: true

- name: Copy headers config file  
  ansible.builtin.copy:  
    src: headers.conf  
    dest: /etc/nginx/snippets/headers.conf
    owner: root
    group: root
    mode: '0644'
    force: true

- name: Copy letsencrypt config file  
  ansible.builtin.copy:  
    src: letsencrypt.conf  
    dest: /etc/nginx/snippets/letsencrypt.conf
    owner: root
    group: root
    mode: '0644'
    force: true
  
- name: Copy ssl config file  
  ansible.builtin.copy:  
    src: ssl.conf  
    dest: /etc/nginx/snippets/ssl.conf
    owner: root
    group: root
    mode: '0644'
    force: true

- name: Enable nginx service
  ansible.builtin.service:
    enabled: true
    name: nginx

- name: Start nginx service
  ansible.builtin.service:
    name: nginx
    state: started
